---
abstract: 'Base class for exceptions'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Exception-Base
provides:
  MooseX::Exception::Base:
    file: lib/MooseX/Exception/Base.pm
    version: v0.0.1
  MooseX::Exception::Base::Stringify:
    file: lib/MooseX/Exception/Base/Stringify.pm
    version: v0.0.1
requires:
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MooseX::Exception::Base
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/MooseX-Exception-Base.git
version: v0.0.1
